### ISSUE TITLE
Could not load file or assembly 'SIPSorceryMedia'

### ISSUE THREAD

**Issue by paulnearney** [sipsorcery/sipsorcery-media#2]
I'm running the code from the RecordIncomingCall example, building in .NET core 3.1.

On receiving a call, it's failing to load the SipSorceryMedia assembly with:

> Exception handling INVITE. Could not load file or assembly 'SIPSorceryMedia, Version=4.0.34.0, Culture=neutral, PublicKeyToken=null'. An attempt was made to load a program with an incorrect format.

It runs fine on my dev machine, but not on the windows server I'm deploying to. The Windows Server has .net core runtime 3.1.3 installed (x86 and x64) and .net core SDK 3.1.201 x64. 

csproj as follows:

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <AssemblyName>SipServer</AssemblyName>
    <Platforms>AnyCPU;x64;x86</Platforms>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <Prefer32Bit>false</Prefer32Bit>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Serilog" Version="2.9.0" />
    <PackageReference Include="Serilog.Extensions.Logging" Version="3.0.1" />
    <PackageReference Include="Serilog.Sinks.Console" Version="3.1.1" />
    <PackageReference Include="SIPSorcery" Version="4.0.35-pre" />
    <PackageReference Include="SIPSorcery.WebSocketSharp" Version="0.0.1" />
    <PackageReference Include="SIPSorceryMedia" Version="4.0.34-pre" />
  </ItemGroup>

</Project>
```

I've tried building as AnyCPU (prefer 32 bit checked and unchecked), x64 and x86 but it fails with the same error each time.

Any thoughts?

**Comment by sipsorcery** [comment]
Try double checking the [Desktop Experience](https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2012-r2-and-2012/dn609826(v%3Dws.11)) feature is installed. It's my understanding it's not installed by default on some versions of Windows Server. and the SIPSorceryMedia dll relies on Windows Media Foundation.

**Comment by paulnearney** [comment]
Of course... bet that's it. Be right back :)

**Comment by paulnearney** [comment]
Hmm. the server is definitely running desktop experience, as I'm RDPing to it and can see the desktop. It didn't have windows media foundation installed - I've installed this and rebooted, but still getting the same issue. 

I also tried starting the Windows Audio service, just in case... but no joy

**Comment by sipsorcery** [comment]
Next thing to check is the [VC++ Runtime](https://support.microsoft.com/en-ie/help/2977003/the-latest-supported-visual-c-downloads). 

If that doesn't work then my next step would be to use the [Dependency Walker](https://www.dependencywalker.com/) utility. It's helpful for spotting missing dll's. Here's a screenshot of a check on my machine which is able to run the application. You should treat the tool as a guide rather than completely trusting it Red errors and question marks can often be false positives.

![depwalker](https://user-images.githubusercontent.com/197660/77930875-520c6080-72a3-11ea-96a4-21422570d32e.png)

**Comment by paulnearney** [comment]
I've been trying dependency walker - I get the same list of errors on a working machine as I do the server that it's failing on! I'll check the C++ runtime

**Comment by paulnearney** [comment]
Thanks Aaron, that sorted it. Great libraries, by the way.
