### ISSUE TITLE
Support for audio streams

### ISSUE THREAD

**Issue by paulnearney** [sipsorcery/sipsorcery-media#3]
I would like to take full control of the audio - i.e. rather than using microphone or music files as the audio source, I'd like to call the Send* methods to send audio. Similarly, I'd like to send received audio elsewhere, rather than playing through the system speakers

I'm using the RecordIncomingCall example. If I set the AudioSource on the RtpAVSession options to "None", I get:

>[16:25:17 WRN] No local media tracks available for create offer.
[16:25:17 WRN] Exception handling INVITE. Object reference not set to an instance of an object.
[16:25:17 WRN] Transaction already exists, ignoring duplicate request, INVITE sip:******.

If I set it to "Silence", I get:

> [16:28:50 WRN] Resending final response for INVITE, sip:*****, cseq=1.

with some interesting noise played down the line to my softphone.

I'm running on a machine without any audio devices attached, as I shouldn't need any for my scenario - i'm wondering if this is the cause of the errors.

Is my scenario supported?

**Comment by sipsorcery** [comment]
You should start by switching `RtpAVSession` to `RTPSession`. The purpose of `RtpAVSession` is to add audio/video capturing and rendering capabilities to `RTPSession`. If you don't need the devices then `RTPSession` is a better starting point.

**Comment by paulnearney** [comment]
OK, thanks - I'm guessing I need to use a SIPServerUserAgent rather than a SIPUserAgent too - is that right?

**Comment by sipsorcery** [comment]
It will be more work to use `SIPServerUserAgent`. For example you would need to manually match any in-dialog requests such as BYE's, re-INVITE's. The `SIPUserAgent` will automatically do that for you.

The main reason to use `SIPServerUserAgent` is if you need more flexibility in your SIP request processing. The classic example is a [SIP B2B User Agent](https://en.wikipedia.org/wiki/Back-to-back_user_agent) (if you're familiar with Asterisk and FreeSWITCH that's how they handle calls). 

If you don't need a full SIP B2B UA a better example to start from is the [SIPCallServer](https://github.com/sipsorcery/sipsorcery/blob/master/examples/SIPCallServer/Program.cs). You could strip out the ability to place calls and replace the `RTPAudioSession` with `RTPSession` and that might be close to what you want.

**Comment by paulnearney** [comment]
OK, thanks - that makes sense. I appreciate the support

**Comment by paulnearney** [comment]
SipUserAgent.Answer() takes an IMediaSession, which RTPSession doesn't implement. I'm thinking I need to implement a new RTPSession class that inherits from RTPSession and implements IMediaSession - and that would also encapsulate my audio inputs/outputs. Is that right?

**Comment by sipsorcery** [comment]
Yes that's correct. 

`RTPSession` deliberately doesn't explicitly implement `IMediaSession` to make it apparent that it does not have any media capture or rendering capabilities.
