### ISSUE TITLE
Implement DTLSHandshake with full c# (Org.BouncyCastle)

### ISSUE THREAD

**Issue by rafcsoares** [sipsorcery/sipsorcery-media#5]
Hello Buddy, thank you very much for this amazing project.

SIPSorcery Media is a good initial point to WebRTC Support in SipSorcery but this implementations in C++ break the original concept of SIPSorcery (full cross platform C# project)

As some classes in SIPSorcery refer to classes in SipSorcery Media (as DtlsHandShake) i think if it is possible to convert DTLSHandshake to C# using reference to Org.BouncyCastle.

As my low Knowledge of C++ i probably cannot do this kind of conversion by myself.

Here another useful repository (this repository use Org.BouncyCastle to implement DTLS)
https://github.com/CreatorDev/DTLS.Net

Best Regards
Rafael

**Comment by sipsorcery** [comment]
It's definitely possible and I agree it'd be nice. See https://github.com/dotnet/runtime/issues/1766 where I and a few others advocated DTLS support for the .Net Core base class library.

But even once a .Net DTLS implementation is available then SRTP will then need to be ported from C++ to C#. And for video (which is the primary use case for WebRTC) a video codec such as VPX/H264 are needed and I doubt it will ever make sense to port those.

So given there will always be some platform specific libraries needed for a WebRTC implementation the motivation to implement/fix a .net version of DTLS isn't high.

As an aside Microsoft Teams uses webrtc and frustratingly Microsoft doesn't provide a nice way to use the those libraries so that Windows or .net developers can write custom webrtc apps. But of interest was that Teams uses TLS instead of DTLS for the webrtc handshake BUT then still seemed to be using UDP for the RTP packets. I didn't think that was possible and haven't checked it out properly yet. If it is a possibility it would mean DTLS isn't required at all and TLS, for which there is a .net implementation, could be used. That still leaves the SRTP and video codecs though, so again not a huge help towards a fully .net version.

**Comment by rafcsoares** [comment]
@sipsorcery you can use BouncyCastle to implement DtlsSrtp Client/Server. As BouncyCastle exists in C# and in Java i'm porting this DtlsSrtpServer (https://www.javatips.net/api/mediaserver-master/rtp/src/main/java/org/restcomm/media/rtp/crypto/DtlsSrtpServer.java#)
to C# (i'm figuring out how to implement the Client).

A full port in C# can benefit Unity Developers (like me), so thats why i'm so interested in this Dtls port

**Comment by sipsorcery** [comment]
Thanks for the link, that is interesting, I'll have a closer look when time permits. If you do get a C# port of the DTLS server working then PR's on this project are always welcome :).

**Comment by rafcsoares** [comment]
Sure, i doing my best to port this to C#

**Comment by sipsorcery** [comment]
I've gone ahead and added a [project](https://github.com/sipsorcery/sipsorcery/projects/3) for this task but TBH I'm not sure when it will get worked on. I did spend some more time looking at the Java code and BouncyCastle and a port looks feasible it's just the time involved.

For my own interest what are you planning on using WebRTC for with Unity? In game video calls? I've spent a tiny bit of time playing around with Unity and it's on my list to dig deeper into it. Also did you look at the Microsoft Mixed Reality group's [webrtc library](https://github.com/microsoft/MixedReality-WebRTC)? If so was there a reason it didn't suit your Unity needs?

**Comment by rafcsoares** [comment]
I trying to implement something like Vuforia Chalk to a Customer.

I tried all WebRTC Libraries but, the problem is the Cross Support.
Unity use Net Standard 2.0, so every c# code can be ported without efforts to it, but when we dig into Native Libraries we are doomed to implement this P/Invokes in Objective-C (For iOS), Java AAR (Android), JavaScript (for WebGL), C++ (For PC),

This WebRTC Library from Mixed Reality only works in Hololens platforms (Like said in description, only works in Hololens x86 and Hololens ARM X86) as it is a wrapper from native C++ DLLs to this specific platforms

I already tried other WebRTC Libraries, like official Unity WebRTC
https://github.com/Unity-Technologies/com.unity.webrtc

but it only work in Linux, PC or Mac with Intel NVIDIA Graphic Card with Direct x12 support because  the whole plugin is a Wrap from C++ Native NVidIa Codecs and native comunications to enable support to Google Stadia

**Comment by rafcsoares** [comment]
Well... o ported huge amount of files to C# (and implemented another ones like DtlsSrtpClient)
I will try test everything before submit a PR.

If possible, try include BouncyCastle to the project so i can submit without major problems

![image](https://user-images.githubusercontent.com/45020302/83340424-f152d180-a2ad-11ea-815f-8ac554288dea.png)

**Comment by sipsorcery** [comment]
Just in case it's of any use a `Go` open source DTLS implementation for WebRTC is available [here](https://github.com/pion/webrtc/blob/master/dtlstransport.go).

**Comment by rafcsoares** [comment]
I'm back to working on DTLS port today, i was working on another project and now i will try again too make this port work

**Comment by rafcsoares** [comment]
Finally finished this implementation!

Tomorrow i will push request to Sipsorcery!
😁😁

**Comment by rafcsoares** [comment]
@sipsorcery after bunch of work i sucessfully made a DTLS Handshake (and SRTP) in full C# as a server, but i can't make it work as a client.

I tested your C++ code, to try to made it work as a Client vs Chrome Server, but it apears to fail too.

Do you know any possible reasons to explain why DTLS Handshake as Client fails?

I tried to debug the code but it seems that chrome don't send the correct hello server msg. Did i miss anything?

Perhaps must send any step before handshake when acting as client?

Best Regards
Rafael


I attached a simple source to test your code as a Client (just rename TXT to CS, github dont accept CS files in attachment)

```
//Code used as Client
var address = peerConnection.IceSession.ConnectedRemoteEndPoint;

int res = dtls.DoHandshakeAsClient((ulong)peerConnection.GetRtpChannel(SDPMediaTypesEnum.audio).RtpSocket.Handle, (short)address.AddressFamily, address.Address.GetAddressBytes(), (ushort)address.Port);
```
[WebRTCTestClientExample.txt](https://github.com/sipsorcery/sipsorcery-media/files/4795988/WebRTCTestClientExample.txt)

**Comment by sipsorcery** [comment]
Thx again for looking at this.

My DTLS client handshake method was missing a few bits. Up until now that method was never being used due to the ICE role  always getting set to passive which meant act as the DTLS server.

I've been looking at it today and the Active/Client role is now working on `master`; tested with Chrome, FireFox and Edge.  The "simplest" test utility I've got is the [icecmdline](https://github.com/sipsorcery/sipsorcery/tree/master/examples/icecmdline) app. To use it start the app and then open the `webrtc.html` in a browser on the same machine and click either of the buttons. Both should successfully handshake.

**Comment by rafcsoares** [comment]
Thanks @sipsorcery i will test it right now, and after that i will take a look if my DTLS Client in full C# is working.

**Comment by sipsorcery** [comment]
In theory in the `icecmdline` app you should be able to remove the `SIPSorceryMedia` project and replace it with your new one. The only thing `SIPSorceryMedia` is being used for is the DTLS handshake.

**Comment by rafcsoares** [comment]
Hello buddy, sorry for the delay (got some personal problems last week)

I created a separate Package to handle with DtlsSrtp for you. 
(as i work with unity, and unity dont understand nuget , i created my git repository in UnityPackageManager format and added NugetPackage for you)

https://www.nuget.org/packages/kyub.org.bouncycastle.dtlssrtp

Example how to create a DtlsSrtpTransport
```
//Create from selfsigned certificate
var certificate = DtlsUtils.CreateSelfSignedCert();
DtlsSrtpTransport dtlsHandle = new DtlsSrtpTransport(
                                    peerConnection.IceRole == IceRolesEnum.active ?
                                    (IDtlsSrtpPeer)new DtlsSrtpClient(certificate) :
                                    (IDtlsSrtpPeer)new DtlsSrtpServer(certificate));

//Also support create from file, for example
//DtlsSrtpTransport dtlsHandle = new DtlsSrtpTransport(
//                                    peerConnection.IceRole == IceRolesEnum.active ?
//                                    (IDtlsSrtpPeer)new DtlsSrtpClient(DTLS_CERTIFICATE_PATH, DTLS_KEY_PATH) :
//                                    (IDtlsSrtpPeer)new DtlsSrtpServer(DTLS_CERTIFICATE_PATH, DTLS_KEY_PATH));

Task.Run(async () => dtlsResult = await DoDtlsHandshake(peerConnection, dtlsHandle))
```

Example of DoDtlsHandshake (Support to Server and Client in same call)

 ```
/* DtlsHandshake requires DtlsSrtpTransport to work.
 * DtlsSrtpTransport is similar to C++ Dtls class combined with Srtp class and can perform Handshake as Server or Client in same call. 
 * The contructor of transport require a DtlsStrpClient or DtlsSrtpServer to work and the method DoHandshake require a socket with support to IPV6 Multiplex and a RemoteEndPoint (RemoteEndPoint will be discarded when performing as Server) */
private static async Task<bool> DoDtlsHandshake(RTCPeerConnection peerConnection, DtlsSrtpTransport dtlsHandle)
{
            Console.WriteLine("DoDtlsHandshake started.");

            var rtpSocket = peerConnection.GetRtpChannel(SDPMediaTypesEnum.audio).RtpSocket;
            var res = dtlsHandle.DoHandshake(rtpSocket, peerConnection.IceSession.ConnectedRemoteEndPoint);

            Console.WriteLine("DtlsContext initialisation result=" + res);

            if (dtlsHandle.IsHandshakeComplete())
            {
                Console.WriteLine("DTLS negotiation complete.");

                peerConnection.SetSecurityContext(
                    dtlsHandle.ProtectRTP,
                    dtlsHandle.UnprotectRTP,
                    dtlsHandle.ProtectRTCP,
                    dtlsHandle.UnprotectRTCP);

                await peerConnection.Start();

                return true;
            }
            else
            {
                return false;
            }
}
```

**Comment by sipsorcery** [comment]
Any chance of access to the source?

**Comment by rafcsoares** [comment]
Sure @sipsorcery , the project is OpenSource

https://gitlab.com/KyubInteractive/unitybouncycastle/-/tree/master/Assets/Org.BouncyCastle.DtlsSrtp

Some Useful methods i created.
Your SIP api work based in X502Certificates from files. My API simplify the process, you can read the certificate from file or create a selfsigned certificate.

All certificate functions can be found inside **DtlsUtils.cs**. Inside this class you can generate a SelfSigned Certificate, or Load from a file. You can get the Fingerprint from Certificate too, so this make possible improve RTCCertificate to use fingerprint from your generated certificate.

```
new RTCCertificate
                            {
                                X_Fingerprint = DTlsUtils.Fingerprint(certificate) //DTLS_CERTIFICATE_FINGERPRINT
                            }
```

i really recommend you to change RTCCertificate to receive X502Certificate instead the path.

**Comment by sipsorcery** [comment]
I get a 404 on from that link.

Is the repo public? Searching on your account name also doesn't yield any results.

[https://gitlab.com/search?utf8=%E2%9C%93&snippets=false&scope=&repository_ref=&search=KyubInteractive](https://gitlab.com/search?utf8=%E2%9C%93&snippets=false&scope=&repository_ref=&search=KyubInteractive)

**Comment by rafcsoares** [comment]
@sipsorcery ops, my bad, i will convert to public now, just a minute

**Comment by rafcsoares** [comment]
@sipsorcery Done.

https://gitlab.com/KyubInteractive/unitybouncycastle/-/tree/master/Assets/Org.BouncyCastle.DtlsSrtp

Dont forget to read my previous commets about how to use DtlSrtpTransport and how to improve RTCCertificate to support Fingerprint from certificate and selfsigned certificates =)

**Comment by sipsorcery** [comment]
Got it thanks. Creating certificates dynamically was on my long list of todo's, be great to tick that one off as well!

**Comment by rafcsoares** [comment]
i'm glad to help this complex project buddy. =)

**Comment by sipsorcery** [comment]
@rafcsoares this is fantastic work and thanks once again for putting the time in!!

I simplified the `DtlsSrtpTransport` a fair bit mainly because the approach I employed of handing over a socket handle doesn't work very well. There ends up being a race condition between the RTP receive loop and the DTLS handshake receive loop. It was on my list to fix this problem in my C++ wrapper class as well. The good thing is now I don't have to.

After replacing the sockets in the `DtlsSrtpTransport` with a memory stream it both simplifies the approach and eliminates the race condition. And I have been able to get both client and server handshakes to work with the `icecmdline` sample with no native C++ library in sight!

My question for you now is what's your plan for your nuget package and repo? I'd like to include your implementation and my changes directly in the main [sipsorcery](https://github.com/sipsorcery/sipsorcery) repo, giving you credit of course. What are your thoughts?

**Comment by sipsorcery** [comment]
And another big advantage of switching to a memory stream is the handshake works seamlessly when using a TURN relay (which wraps the DTLS packets up in STUN Data Indications).

**Comment by rafcsoares** [comment]
Go ahead!
I just separate this implementation in another repository because this code, like bouncy castle inself, can be useful for someone else. 

My main plan is to make this work with SipSorcery.

Nice to know the aprouch of memory stream, i saw this race conditions a bunch of times.... thats why i added a "Random" retransmission time inside Read method of DtlsSrtpTransport... Good to know that you can simplify the process with a memory stream.

Doing this inside Sip main source you can omit the handshake process from final user :)

**Comment by rafcsoares** [comment]
@sipsorcery i saw a minor problem in your Read function in DtlsSrtpTransport.

Your final result when everthing fails is 0.
You must return -1 to BouncyCastle  retransmit the packets when, after waittime, the amount of data obtained is empty.

Another possible problem is that your read function don't contain a Skip time to abort DtlsHandshake when this take too long.

**Comment by sipsorcery** [comment]
Thx for the tips. My effort so far was to prove that it worked. It does! Now I'll go back and clean things up.

**Comment by sipsorcery** [comment]
@rafcsoares any chance you could drop me an email at aaron@sipsorcery.com?

**Comment by rafcsoares** [comment]
@sipsorcery done

**Comment by sipsorcery** [comment]
New DTLS/SRTP logic is now in the main sipsorcery code base and nuget package v4.0.58-pre.
